
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data

  pgadmin:
    pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin4
      restart: on-failure
      ports:
        - "8888:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: onlineshop@gmail.com
        PGADMIN_DEFAULT_PASSWORD: postgres
      volumes:
        - pgadmin-data:/var/lib/pgadmin

volumes:
  postgresdata
  pgadmin-data